name: 'test'
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: build
  cancel-in-progress: true

jobs:
  pkgbuild-versions:
    permissions:
      contents: write
      packages: write
    strategy:
      matrix:
        pkgbuild: ["PKGBUILD.any", "PKGBUILD.multi"]
        runs-on: [buildjet-4vcpu-ubuntu-2204-arm, ubuntu-latest]
    runs-on: ${{ matrix.runs-on }}
    container:
      image: docker://manjarolinux/build:latest
    steps:
      - name: check out repo for action code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - name: pkgbuild
        uses: ./
        with:
          pkgbuild: ${{ matrix.pkgbuild }}
